@startuml
!include ../_style.puml
title ВИ-01 «Оформить покупку билета»: диаграмма коммуникации

object "<u>: Зритель</u>" as user
object "<u>ui: Витрина</u>" as ui
object "<u>app: Сервис продаж</u>" as app
object "<u>repo: БилетыDAO</u>" as repo
object "<u>pay: Платёжный шлюз</u>" as pay

user -- ui : 1: выбратьМесто(сектор, ряд) >
ui -- app : 1.1: заблокировать(место) >
app -- repo : 1.1.1: сохранитьБлокировку(место) >
user -- ui : 2: ввестиРеквизиты(данные) >
ui -- app : 2.1: оплатить(данные, сумма) >
app -- pay : 2.1.1: авторизовать(данные, сумма) >
app -- repo : 2.1.2: сохранить(билет) >
app -- ui : 3: билет <
@enduml