@startuml
!include ../_style.puml

actor "Покупатель" as buyer
participant "Витрина" as ui
participant "Сервис продаж" as app
database "БД" as db

buyer -> ui: выбрать место
ui -> app: запрос на бронирование
app -> db: INSERT блокировка
db --> app: ok
app --> ui: место заблокировано
ui --> buyer: переход к оплате

@enduml