@startuml
!include ../_style.puml
title Процесс «Покупка билета» с потоком объектов

start
: Выбрать событие и место;
: Заказ [черновик] /

: Заблокировать место на время оплаты;
: Заказ [ожидает оплаты] /

: Оплатить через платёжный шлюз;
if (Оплата успешна?) then (да)
    : Заказ [оплачен] /
    
    : Создать электронный билет;
    : Заказ [выполнен] /
    
    : Отправить билет на email зрителя;
    stop
else (нет)
    : Снять временную блокировку;
    : Заказ [отменён] /
    stop
endif
@enduml