@startuml
!include ../_style.puml
title Жизненный цикл объекта «Заказ»

hide empty description

state Черновик
state ОжидаетОплаты
state Оплачен {
    state ГенерацияБилетов
    state ГотовКОтправке
    
    [*] --> ГенерацияБилетов
    ГенерацияБилетов --> ГотовКОтправке : данныеЗаписаны
    ГотовКОтправке --> [*]
}
state Выполнен
state Возврат
state Отменён

Черновик: entry / создатьИдентификатор()

[*] --> Черновик
Черновик --> ОжидаетОплаты : подтвердитьВыбор() [места свободны]
ОжидаетОплаты --> Черновик : изменитьВыбор()
ОжидаетОплаты --> Отменён : after(15 мин) / снятьБлокировку()
ОжидаетОплаты --> Оплачен : оплатаПоступила

Оплачен --> Выполнен : отправитьБилеты()

Выполнен --> Возврат : оформитьВозврат() [до матча > 3 дней]
Возврат --> Отменён : / вернутьДеньги()

Выполнен --> [*]
Отменён --> [*]
@enduml